### PR TITLE
Bringing good old reports to PHP 7.1 and SSL days

### PR DESCRIPTION
**Pull request by EthraZa**
Fixes for open_basedir, mysqli_ and https

### CODE REVIEW

**Comment by taq** [comment]
Hey, thanks for your code! I'll take a closer look on it. There's a long time I don't test PHPReports with MySQL, and to be honest, any PHP code with MySQL, so now we have a new interface to MySQL?

**Review by taq — COMMENTED** [review]
I'm not sure about using require inside a method, could you move the require clauses to the top of the file?

**Review by taq — COMMENTED** [review]
What about just using is_resource and not is_array or is_object? I think with just is_resource we can be sure $oCon is a valid connection. :-)

**Comment by EthraZa** [comment]
Hi, I have just changed what you asked. 
About the connection test, the other day it was too late at night and I was not thinking at all. I have reverted it to the original test for the other databases and added mysql to the ignored databases, but added a truthy check that works for SQLite3 and MySQL/MariaDB.
Hehe, yep mysql_ was dropped for some time now, I just wish phpreports to use PDO instead, but mysqli_ will do.

**Comment by taq** [comment]
PDO was just a concept when I started it. :-)

I'll take a look on the new code right now.

**Comment by taq** [comment]
Seems everything is ok, thanks for your code! :-)

**Pull request merged**
